name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

env:
  app_name: lat
  app_repo: lat-opensource/lat
  
jobs:
  check-binaries:
    runs-on: ubuntu-slim
    outputs:
      app_version: ${{ steps.get-version.outputs.app_version }}
      app_build: ${{ steps.check-release.outputs.app_build }}
    steps:
      - uses: actions/checkout@v6

      - name: Get Version
        id: get-version
        run: |
          app_version=$(curl -sSL "https://github.com/${{ env.app_repo }}/raw/refs/heads/master/VERSION")
          if [ -z "${app_version}" ] || [ "${app_version}" == "null" ]; then
            echo "Failed to get version"
            exit 1
          fi
          
          echo "app_version=${app_version}" >> $GITHUB_ENV
          echo "app_version=${app_version}" >> $GITHUB_OUTPUT
          echo ""
          echo "========== Build Args =========="
          echo "app_version=${app_version}"

  build-binaries:
    runs-on: ubuntu-latest
    needs: check-binaries
    env:
      app_version: ${{ needs.check-binaries.outputs.app_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'debian', 'loongnix' ]
        include:
          - os: 'debian'
            suite: 'trixie'
          - os: 'loongnix'
            suite: '25'

    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.app_name }}-${{ matrix.os }}-${{ matrix.suite }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.app_name }}-${{ matrix.os }}-${{ matrix.suite }}-build-
            ${{ runner.os }}-buildx-

      - name: Build Binaries
        run: |
          docker buildx build --platform linux/loong64 --build-arg BASE_IMAGE=ghcr.io/loong64/${{ matrix.os }}:${{ matrix.suite }}-slim --build-arg VERSION=${{ env.app_version }} -t ${{ env.app_name }}-${{ matrix.os }}-${{ matrix.suite }}:${{ env.app_version }}-loong64 --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max . --load
          docker run --rm -v $(pwd)/dist:/dist ${{ env.app_name }}-${{ matrix.os }}-${{ matrix.suite }}:${{ env.app_version }}-loong64

      - name: Upgrade Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.app_name }}-${{ matrix.os }}-${{ matrix.suite }}
          path: ${{ github.workspace }}/dist/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
